name: Docker 
on:
  push: 
    branches: [main]
jobs: 
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4 # Loyiha kodini yuklash
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      # ðŸ‘‡ MUAMMONI HAL QILUVCHI QADAM
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          # Sizning GitHub Variables/Secrets dan foydalanish
          username: ${{ vars.DOCKERHUB_USERNAME }} 
          password: ${{ secrets.DOCKERHUB_TOKEN }} # Secret orqali token chaqirildi
          # logout: true qolishi mumkin, ammo kerak emas
          
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: shokhijakhondev/cicd_github_actions:latest
